import numpy as np
import matplotlib as mpl
import matplotlib
matplotlib.use('Qt5Agg')  # Use Qt5 interactive backend
import matplotlib.pyplot as plt
from matplotlib import font_manager

# === IEEE-like font family and sizes (10pt doc) ===
S = {
    "normalsize": 18,      # body text
    "small": 16,            # axis labels / lane labels
    "footnotesize": 14,     # tick labels / legend
    "large": 22,           # figure title
}
mpl.rcParams.update({
    "text.usetex": False,
    "mathtext.fontset": "stix",                   # Times-like math
    "axes.titlesize": S["large"],
    "axes.labelsize": S["small"],
    "xtick.labelsize": S["footnotesize"],
    "ytick.labelsize": S["footnotesize"],
    "legend.fontsize": S["footnotesize"],
    "pdf.fonttype": 42, "ps.fonttype": 42,        # keep text searchable
})

# Pick an available Times-like font so figures stay consistent on systems
# without proprietary Times faces.
_FONT_CANDIDATES = [
    "Times New Roman",
    "Times",
    "Nimbus Roman",
    "DejaVu Serif",
    "STIXGeneral",
]


def _select_font_property():
    for family in _FONT_CANDIDATES:
        prop = font_manager.FontProperties(family=family)
        try:
            font_manager.findfont(prop, fallback_to_default=False)
        except ValueError:
            continue
        return prop
    return font_manager.FontProperties(family="serif")


_BASE_FONT = _select_font_property()


def font_prop(size_key: str) -> font_manager.FontProperties:
    prop = _BASE_FONT.copy()
    prop.set_size(S[size_key])
    return prop


def plot_cvae_vs_fop_3d(
    d_cvae, sv_cvae, t_cvae,
    d_range=(-4.0, 4.0), sv_range=(0.0, 15.0), t_range=(0.5, 5.0),
    d_bins=9, sv_bins=8, t_bins=6,
    fop_subsample=1,            # >1 时对网格做稀释，避免太密看不清
    elev=18, azim=45,
    save_path=None
):
    """
    CVAE samples: 3 arrays of same length (N,)
    FOP grid: generated by linspace ranges with (d_bins, sv_bins, t_bins)
    """
    d_cvae = np.asarray(d_cvae).reshape(-1)
    sv_cvae = np.asarray(sv_cvae).reshape(-1)
    t_cvae = np.asarray(t_cvae).reshape(-1)
    assert len(d_cvae) == len(sv_cvae) == len(t_cvae), "CVAE arrays must have same length"

    # --- FOP grid (structured sampling) ---
    d_grid = np.linspace(d_range[0], d_range[1], d_bins)
    sv_grid = np.linspace(sv_range[0], sv_range[1], sv_bins)
    t_grid = np.linspace(t_range[0], t_range[1], t_bins)
    D, SV, T = np.meshgrid(d_grid, sv_grid, t_grid, indexing="ij")
    D = D.ravel()
    SV = SV.ravel()
    T = T.ravel()

    # Optional: subsample grid points to reduce clutter
    if fop_subsample > 1:
        idx = np.arange(len(D))[::fop_subsample]
        D, SV, T = D[idx], SV[idx], T[idx]

    # --- Plot ---
    fig = plt.figure(figsize=(7.0, 5.8))
    ax = fig.add_subplot(111, projection="3d")

    # FOP grid (gray, structured)
    ax.scatter(
        D, SV, T,
        s=10,
        alpha=0.20,
        c="gray",
        marker="s",
    )

    # CVAE samples (colored, sparse)
    ax.scatter(
        d_cvae, sv_cvae, t_cvae,
        s=9,
        alpha=0.35,
        c=t_cvae,
        marker="o",
    )

    ax.set_xlabel(r"$d$ (lateral offset)", fontproperties=font_prop("small"))
    ax.set_ylabel(r"$\dot{s}$ (longitudinal velocity)", fontproperties=font_prop("small"))
    ax.set_zlabel(r"$t$ (time horizon)", fontproperties=font_prop("small"))

    ax.set_xlim(d_range)
    ax.set_ylim(sv_range)
    ax.set_zlim(t_range)

    ax.view_init(elev=elev, azim=azim)

    # Apply tick label fonts
    for tick in ax.get_xticklabels():
        tick.set_fontproperties(font_prop("footnotesize"))
    for tick in ax.get_yticklabels():
        tick.set_fontproperties(font_prop("footnotesize"))
    for tick in ax.get_zticklabels():
        tick.set_fontproperties(font_prop("footnotesize"))

    plt.tight_layout()

    if save_path:
        plt.savefig(save_path, dpi=300, bbox_inches="tight")
    plt.show()


def plot_fop_3d(
    d_range=(-1.0, 1.0), sv_range=(0.0, 14.0), t_range=(3.0, 5.0),
    d_bins=10, sv_bins=10, t_bins=10,
    elev=18, azim=45,
    save_path=None
):
    """
    Plot FOP structured sampling grid in 3D space.
    d: lateral offset [m]
    sv: longitudinal velocity [m/s]
    t: time horizon [s]
    """
    # --- FOP grid (structured sampling) ---
    d_grid = np.linspace(d_range[0], d_range[1], d_bins)
    sv_grid = np.linspace(sv_range[0], sv_range[1], sv_bins)
    t_grid = np.linspace(t_range[0], t_range[1], t_bins)
    D, SV, T = np.meshgrid(d_grid, sv_grid, t_grid, indexing="ij")
    D = D.ravel()
    SV = SV.ravel()
    T = T.ravel()

    # --- Plot ---
    fig = plt.figure(figsize=(7.0, 5.8))
    ax = fig.add_subplot(111, projection="3d")

    # FOP grid (blue, structured)
    ax.scatter(
        D, SV, T,
        s=15,
        alpha=0.7,
        c="blue",
        marker="o"
    )

    ax.set_xlabel(r"$d$ [m]", fontproperties=font_prop("small"))
    ax.set_ylabel(r"$\dot{s}$ [m/s]", fontproperties=font_prop("small"))
    ax.set_zlabel(r"$t$ [s]", fontproperties=font_prop("small"))

    ax.set_xlim(d_range)
    ax.set_ylim(sv_range)
    ax.set_zlim(t_range)

    ax.view_init(elev=elev, azim=azim)

    # Apply tick label fonts
    for tick in ax.get_xticklabels():
        tick.set_fontproperties(font_prop("footnotesize"))
    for tick in ax.get_yticklabels():
        tick.set_fontproperties(font_prop("footnotesize"))
    for tick in ax.get_zticklabels():
        tick.set_fontproperties(font_prop("footnotesize"))

    plt.tight_layout()

    if save_path:
        plt.savefig(save_path, dpi=300, bbox_inches="tight")
    plt.show()


if __name__ == "__main__":
    # Plot FOP sampling space only
    plot_fop_3d(
        d_range=(-1, 1),      # lateral offset: [-1, 1] m
        sv_range=(0, 14),     # longitudinal velocity: [0, 14] m/s
        t_range=(3, 5),       # time horizon: [3, 5] s
        d_bins=10,             # number of d samples
        sv_bins=10,            # number of s_dot samples
        t_bins=10,             # number of t samples
        elev=18, azim=45
    )
